sudo: false
language: java
jdk:
  - oraclejdk8
addons:
  firefox: "38.8.0esr"
cache:
  directories:
    - $HOME/.m2

install:
  - export CARGO_DAEMON_WEBAPP_VERSION=1.6.2

before_script:
  - cat /etc/hosts
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mvn dependency:copy -Dartifact=org.codehaus.cargo:cargo-daemon-webapp:${CARGO_DAEMON_WEBAPP_VERSION}:war -DoutputDirectory=./target/.
  - java -jar ./target/cargo-daemon-webapp-${CARGO_DAEMON_WEBAPP_VERSION}.war &

script:
  - mvn -U install -Dmaven.test.skip=true
  - mvn -U cargo:daemon-start
  - mvn -U test
